# Generated by Django 4.1.3 on 2022-11-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('cart_image', models.ImageField(upload_to='photos/cartegories')),
            ],
            options={
                'verbose_name': 'Cartegory',
                'verbose_name_plural': 'Cartegories',
            },
        ),
    ]
