# Generated by Django 4.1.3 on 2022-11-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
